### PR TITLE
Road

### PR DESCRIPTION
**Pull request by tikhonsmovzh**

### CODE REVIEW

**Comment by Kachalk1n** [comment]
very good generating of road 5 stars very fantastic super duper kirill pridurok

**Comment by tikhonsmovzh** [comment]
where is memory clearing?

**Comment by tikhonsmovzh** [comment]
cog HORRIBLE

**Comment by tikhonsmovzh** [comment]
the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE 
the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE the code is HORRIBLE

**Pull request merged**
